FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json npm-shrinkwrap.json ./

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && npm install \
    && mv node_modules node_modules_cache \
    && rm -rf package.json npm-shrinkwrap.json /tmp/*
